# Generated by Django 2.1.4 on 2018-12-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=10)),
                ('petId', models.CharField(max_length=4)),
                ('gender', models.CharField(max_length=1)),
                ('year', models.IntegerField()),
                ('kind', models.CharField(max_length=10)),
            ],
        ),
    ]
