# Generated by Django 2.1.4 on 2018-12-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0002_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
